name = "pairlab-site"
compatibility_date = "2026-07-13"
main = "./src/worker.ts"

[assets]
directory = "./dist"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"
binding = "ASSETS"
run_worker_first = [
  "/",
  "/index.html",
  "/research",
  "/research/*",
  "/people",
  "/people/*",
  "/join",
  "/join/*",
  "/api/*",
  "/publications",
  "/publications/*",
  "/PATCH",
  "/PATCH/*",
  "/trimanpolicy-site",
  "/trimanpolicy-site/*",
  "/AutoIntervene",
  "/AutoIntervene/*",
]
