export type Publication = {
  id: string
  year: number
  venue: string
  title: string
  authors: string
  url?: string
}

export const publications: Publication[] = [
  {
    id: '01',
    year: 2026,
    venue: 'IROS 2026 · To appear',
    title: 'PPReg: Prior-Guided Photometric Registration of 3D Gaussian Splats in Low-Overlap Scenes',
    authors: 'Z. Yuan, T. Zhang, M. Johnson-Roberson, W. Zhi',
  },
  {
    id: '02',
    year: 2026,
    venue: 'IROS 2026 · To appear',
    title: 'Bi-Manual Joint Camera Calibration and Scene Representation',
    authors: 'H. Tang, T. Zhang, M. Johnson-Roberson, W. Zhi',
  },
  {
    id: '03',
    year: 2026,
    venue: 'IROS 2026 · To appear',
    title: 'SOFTMAP: Sim2Real Soft Robot Forward Modeling via Topological Mesh Alignment and Physics Prior',
    authors: 'Z. Ma, U. Yoo, J. Francis, W. Zhi, J. Ichnowski, J. Oh',
  },
  {
    id: '04',
    year: 2026,
    venue: 'ICRA 2026',
    title: 'Joint Flow Trajectory Optimization for Feasible Robot Motion Generation from Video Demonstrations',
    authors: 'X. Dong, M. Johnson-Roberson, W. Zhi',
  },
  {
    id: '05',
    year: 2026,
    venue: 'ICRA 2026',
    title: 'Bi-Manual Joint Camera Calibration and Scene Representation',
    authors: 'H. Tang, T. Zhang, M. Johnson-Roberson, W. Zhi',
  },
  {
    id: '06',
    year: 2026,
    venue: 'ICRA 2026',
    title: 'Efficient Construction of Implicit Surface Models from a Single Image for Motion Generation',
    authors: 'W. T. Chu, T. Zhang, M. Johnson-Roberson, W. Zhi',
  },
  {
    id: '07',
    year: 2026,
    venue: 'ICRA 2026',
    title: 'Cross-Modal Instructions for Robot Motion Generation',
    authors: 'W. Baron, X. Dong, M. Johnson-Roberson, W. Zhi',
  },
  {
    id: '08',
    year: 2026,
    venue: 'ICRA 2026',
    title: 'Infinite Leagues under the Sea: Photorealistic 3D Underwater Terrain Generation by Latent Fractal Diffusion Models',
    authors: 'T. Zhang, W. Zhi, J. Mangelson, M. Johnson-Roberson',
  },
  {
    id: '09',
    year: 2026,
    venue: 'RA-L 2026 · ICRA 2026',
    title: 'Robust Bayesian Scene Reconstruction with Retrieval-Augmented Priors for Precise Grasping and Planning',
    authors: 'H. Wright, W. Zhi, M. Matak, M. Johnson-Roberson, T. Hermans',
  },
  {
    id: '10',
    year: 2026,
    venue: 'RA-L 2026 · ICRA 2026',
    title: 'DOSE3: Diffusion-Based Unified Out-of-Distribution Detection on SO(3) Trajectories',
    authors: 'H. Cheng, T. Zheng, Z. Ma, T. Zhang, M. Johnson-Roberson, W. Zhi',
  },
  {
    id: '11',
    year: 2025,
    venue: 'NeurIPS 2025',
    title: 'From Single Images to Motion Policies via Video-Generation Environment Representations',
    authors: 'W. Zhi, Z. Ma, T. Zhang, M. Johnson-Roberson',
  },
  {
    id: '12',
    year: 2025,
    venue: 'RA-L 2025 · ICRA 2025',
    title: 'RecGS: Removing Water Caustic with Recurrent Gaussian Splatting',
    authors: 'T. Zhang, W. Zhi, et al.',
  },
  {
    id: '13',
    year: 2025,
    venue: 'T-RO 2025 · IROS 2025',
    title: 'Multi-query Robotic Manipulator Task Sequencing with Gromov-Hausdorff Approximations',
    authors: 'F. Sukkar, J. Wakulicz, K. M. B. Lee, W. Zhi, R. Fitch',
  },
  {
    id: '14',
    year: 2025,
    venue: 'RA-L 2025 · IROS 2025',
    title: 'ModCube: Modular, Self-Assembling Cubic Underwater Robot',
    authors: 'J. Zheng, et al., W. Zhi, D. Fan',
  },
  {
    id: '15',
    year: 2025,
    venue: 'Expert Systems with Applications 2025',
    title: 'Pedestrian Trajectory Prediction Using Goal-Driven and Dynamics-Based Deep Learning Framework',
    authors: 'H. Wang, W. Zhi, G. Batista, R. Chandra',
  },
  {
    id: '16',
    year: 2024,
    venue: 'RA-L 2024 · ICRA 2025',
    title: 'Simultaneous Geometry and Pose Estimation of Grasped Objects via 3D Foundation Models',
    authors: 'W. Zhi, H. Tang, T. Zhang, M. Johnson-Roberson',
  },
  {
    id: '17',
    year: 2024,
    venue: 'RA-L 2024 · ICRA 2025',
    title: 'Unifying Representation and Calibration with 3D Foundation Models',
    authors: 'W. Zhi, H. Tang, T. Zhang, M. Johnson-Roberson',
  },
  {
    id: '18',
    year: 2024,
    venue: 'IROS 2024',
    title: 'Diagrammatic Instructions to Specify Spatial Objectives and Constraints with Applications to Mobile Base Placement',
    authors: 'Q. Sun, W. Zhi, T. Zhang, M. Johnson-Roberson',
  },
  {
    id: '19',
    year: 2024,
    venue: 'IROS 2024',
    title: 'V-PRISM: Probabilistic Mapping of Unknown Tabletop Scenes',
    authors: 'H. Wright, W. Zhi, M. Johnson-Roberson, T. Hermans',
  },
  {
    id: '20',
    year: 2024,
    venue: 'IROS 2024',
    title: 'DarkGS: Learning Neural Illumination and 3D Gaussians Relighting for Robotic Exploration in the Dark',
    authors: 'T. Zhang, K. Huang, W. Zhi, M. Johnson-Roberson',
  },
  {
    id: '21',
    year: 2024,
    venue: 'IROS 2024',
    title: 'Learning for Kinodynamic Tree Expansion',
    authors: 'T. Lai, W. Zhi, T. Hermans, F. Ramos',
  },
  {
    id: '22',
    year: 2024,
    venue: 'ICRA 2024',
    title: 'Instructing Robots by Sketching: Learning from Demonstration via Probabilistic Diagrammatic Teaching',
    authors: 'W. Zhi, T. Zhang, M. Johnson-Roberson',
    url: 'https://arxiv.org/abs/2309.03835',
  },
  {
    id: '23',
    year: 2024,
    venue: 'ICRA 2024',
    title: 'Pedestrian Trajectory Prediction Using Dynamics-Based Deep Learning',
    authors: 'H. Wang, W. Zhi, G. Batista, R. Chandra',
  },
  {
    id: '24',
    year: 2023,
    venue: 'ICRA 2023',
    title: 'Global and Reactive Motion Generation with Geometric Fabric Command Sequences',
    authors: 'W. Zhi, I. Akinola, K. Van Wyk, N. Ratliff, F. Ramos',
    url: 'https://ieeexplore.ieee.org/document/10160965',
  },
  {
    id: '25',
    year: 2022,
    venue: 'ICML 2022',
    title: 'Learning Efficient and Robust Ordinary Differential Equations via Invertible Neural Networks',
    authors: 'W. Zhi, T. Lai, L. Ott, E. V. Bonilla, F. Ramos',
    url: 'https://proceedings.mlr.press/v162/zhi22a/zhi22a.pdf',
  },
  {
    id: '26',
    year: 2022,
    venue: 'L4DC 2022 · Best Paper Award',
    title: 'Diffeomorphic Transforms for Generalised Imitation Learning',
    authors: 'W. Zhi, T. Lai, L. Ott, F. Ramos',
    url: 'https://proceedings.mlr.press/v168/zhi22a/zhi22a.pdf',
  },
  {
    id: '27',
    year: 2021,
    venue: 'CoRL 2021',
    title: 'Parallelised Diffeomorphic Sampling-Based Motion Planning',
    authors: 'T. Lai, W. Zhi, T. Hermans, F. Ramos',
    url: 'https://arxiv.org/abs/2108.11775',
  },
  {
    id: '28',
    year: 2021,
    venue: 'IROS 2021',
    title: 'Probabilistic Trajectory Prediction with Structural Constraints',
    authors: 'W. Zhi, L. Ott, F. Ramos',
    url: 'https://arxiv.org/abs/2107.04193',
  },
  {
    id: '29',
    year: 2021,
    venue: 'IROS 2021',
    title: 'Trajectory Generation in New Environments from Past Experiences',
    authors: 'W. Zhi, T. Lai, L. Ott, F. Ramos',
    url: 'https://ieeexplore.ieee.org/document/9636231/',
  },
  {
    id: '30',
    year: 2021,
    venue: 'ICRA 2021',
    title: 'Anticipatory Navigation in Crowds by Probabilistic Prediction of Pedestrian Future Movements',
    authors: 'W. Zhi, T. Lai, L. Ott, F. Ramos',
    url: 'https://ieeexplore.ieee.org/abstract/document/9561022',
  },
  {
    id: '31',
    year: 2019,
    venue: 'CoRL 2019',
    title: 'Kernel Trajectory Maps for Multi-Modal Probabilistic Motion Prediction',
    authors: 'W. Zhi, L. Ott, F. Ramos',
    url: 'https://proceedings.mlr.press/v100/zhi20a.html',
  },
  {
    id: '32',
    year: 2019,
    venue: 'RA-L · IROS 2019',
    title: 'Spatiotemporal Learning of Directional Uncertainty in Urban Environments with Kernel Recurrent Mixture Density Networks',
    authors: 'W. Zhi, R. Senanayake, L. Ott, F. Ramos',
    url: 'https://ieeexplore.ieee.org/abstract/document/8772158',
  },
  {
    id: '33',
    year: 2019,
    venue: 'ICRA 2019',
    title: 'Continuous Occupancy Map Fusion with Fast Bayesian Hilbert Maps',
    authors: 'W. Zhi, R. Senanayake, L. Ott, F. Ramos',
    url: 'https://ieeexplore.ieee.org/abstract/document/8793508/',
  },
]
